name: Deploy Chatbot AWS Infra

on:
  push:
    branches:
      - main

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Install dependencies
        run: |
          poetry export -f requirements.txt --output requirements.txt && \
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy Chatbot Vpc
        run: |
          cdk deploy ChatbotVpcStack --require-approval never

#      - name: Deploy Chatbot Vpc
#        uses: youyo/aws-cdk-github-actions@v2
#        with:
#          cdk_subcommand: deploy
#          cdk_stack: ChatbotVpcStack
#          cdk_args: "--require-approval never"
#          actions_comment: false
